[package]
name = "config"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "6.0.0"
inquire = "0.7.5"
lazy_static = "1.5.0"
serde = { version = "1.0.217", features = ["derive"] }
toml = "0.8.19"
url = { version = "2.5.4", features = ["serde"] }
