[package]
name = "services-test"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
nanoid = "0.4.0"
reqwest = { version = "0.12.12", features = ["multipart", "stream"] }
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread"] }
